# Generated by Django 4.1.1 on 2022-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beat_name', models.CharField(help_text='Enter beat name', max_length=50)),
                ('producer', models.CharField(help_text='Enter producer name', max_length=50)),
                ('artwork', models.ImageField(help_text='Upload artwork', upload_to='ls_app/media')),
                ('the_file', models.FileField(help_text='Upload beat', upload_to='ls_app/media')),
                ('genre', models.CharField(choices=[('HipHop', 'HipHop'), ('Dancehall', 'Dancehall')], default=1, help_text='Enter beat genre', max_length=20)),
                ('beat_type', models.CharField(choices=[('Free', 'Free'), ('Buy', 'Buy')], default=1, help_text='Enter beat Type', max_length=20)),
                ('rel_date', models.DateField(help_text='Enter beat release date')),
            ],
        ),
    ]
