apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lsapp
  name: lsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lsapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: lsapp
    spec:
      containers:
        - args:
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_EMAIL
                  name: env
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGADMIN_DEFAULT_PASSWORD
                  name: env
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  key: PGDATABASE
                  name: env
            - name: PGHOST
              value: db
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGPASSWORD
                  name: env
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  key: PGPORT
                  name: env
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: PGUSER
                  name: env
            - name: POSTGRES_DB
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
          image: takudzwachikanga/livesounds:v1
          name: ls-container
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /home/livesounds
              name: lsapp-claim0
      restartPolicy: Always
      volumes:
        - name: lsapp-claim0
          persistentVolumeClaim:
            claimName: lsapp-claim0
        # - name: myvol
        #   hostPath:
        #     path: /home/user/mbidho/ls_project
status: {}
