version: '3'

services:
  lsapp:
    build: .
    volumes:
      - .:/livesounds
    ports:
      - 8000:8000
    image: lsapp:v1
    container_name: ls_container
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      # - ./ls_app/media:/var/lib/postgresql/data
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=livesoundsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chikangapostgre
    ports:
      - "5432:5432"
    container_name: postgres_db
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
