version: '3'

services:
  lsapp:
    # build: .
    image: takudzwachikanga/lsapp:v1
    volumes:
      - .:/livesounds
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGHOST=db
      - PGPORT=$PGPORT
    container_name: ls-container
    labels:
      kompose.service.expose: "true"
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db

  db:
    image: takudzwachikanga/postgres:v1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
    ports:
      - "5432:5432"
    container_name: postgres-db
    labels:
      kompose.service.expose: true
    restart: always
    # depends_on:
    #   - pgadmin

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   volumes:
  #     - ./data/pgadmin-data:/var/lib/pgadmin/data
  #   env_file: .env
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL
  #     - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD
  #   ports:
  #     - "80:80"
volumes:
  data: