version: '3'

services:
  app:
    build: .
    volumes:
      - .:/livesounds
    ports:
      - 8000:8000
    image: lsapp:v1
    container_name: ls_container
    command: python manage.py runserver 0.0.0.0:8000