apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    enviroment: livesounds
  name: ls-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ls-app
      enviroment: livesounds
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ls-app
        enviroment: livesounds
    spec:
      containers:
      - name: ls-container
        image: takudzwachikanga/lsapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
  labels:
    enviroment: pg-admin
spec:
  selector:
    matchLabels:
      app: db-server
      enviroment: pg-admin
  template:
    metadata:
      labels:
        app: db-server
        enviroment: pg-admin
    spec:
      containers:
      - name: db-server
        image: dpage/pgadmin4
        env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: root@root.com
          - name: PGADMIN_DEFAULT_PASSWORD
            value: root
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        


