name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          cd ls_project
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 ls_project --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 ls_project --count --max-complexity=10 --max-line-length=127 --statistics

      # - name: Run unit tests with nose
      #   run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
          
